- name: Deploy etcd cluster
  hosts: etcd_nodes
  vars_files:
    - vars.yml

  tasks:
    - name: Include etcd deployment tasks
      ansible.builtin.include_role:
        name: etcd
        tasks_from: deploy.yml