- name: Start etcd cluster
  hosts: etcd_nodes
  vars_files:
    - vars.yml

  tasks:
    - name: Include etcd start tasks
      ansible.builtin.include_role:
        name: etcd
        tasks_from: start.yml