- name: Start services
  hosts: etcd_nodes
  vars_files:
    - vars.yml
    
  tasks:
    - name: Start etcd block
      block:
        - name: Include etcd start tasks
          ansible.builtin.include_role:
            name: etcd
            tasks_from: start.yml
      tags: etcd

    - name: Start ScyllaDB block
      block:
        - name: Include ScyllaDB start tasks
          ansible.builtin.include_role:
            name: scylla
            tasks_from: start.yml
      tags: scylla

    - name: Start Redpanda block
      block:
        - name: Include redpanda start tasks
          ansible.builtin.include_role:
            name: redpanda
            tasks_from: start.yml
      tags: redpanda