- name: Stop services
  hosts: etcd_nodes
  vars_files:
    - vars.yml
    
  tasks:
    - name: Stop etcd block
      block:
        - name: Include etcd stop tasks
          ansible.builtin.include_role:
            name: etcd
            tasks_from: stop.yml
      tags: etcd

    - name: Stop ScyllaDB block
      block:
        - name: Include ScyllaDB stop tasks
          ansible.builtin.include_role:
            name: scylla
            tasks_from: stop.yml
      tags: scylla

    - name: Stop redpanda block
      block:
        - name: Include redpanda stop tasks
          ansible.builtin.include_role:
            name: redpanda
            tasks_from: stop.yml
      tags: redpanda