- name: Create etcd user
  become: true
  ansible.builtin.user:
    name: etcd
    shell: /bin/false
    system: true
    create_home: false

- name: Create data directory
  become: true
  ansible.builtin.file:
    path: /var/lib/etcd
    state: directory
    owner: etcd
    group: etcd
    mode: '0755'

- name: Download and unarchive etcd
  ansible.builtin.unarchive:
    src: https://github.com/etcd-io/etcd/releases/download/v3.5.21/etcd-v3.5.21-linux-amd64.tar.gz
    dest: /tmp/
    remote_src: true
    creates: /tmp/etcd-v3.5.21-linux-amd64/etcd

- name: Copy etcd binaries to /usr/local/bin
  become: true
  ansible.builtin.copy:
    src: "/tmp/etcd-v3.5.21-linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    remote_src: true
    mode: '0755'
  loop:
    - etcd
    - etcdctl

- name: Create systemd service file from template
  become: true
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true